### PR TITLE
Added New FunctionDataCSV function to the structures.

### PR DESCRIPTION
**Pull request by lucasiturbide**
This adds the function and structures for the new FunctionDataCSV

### CODE REVIEW

**Comment by lucasiturbide** [comment]
Hi Justin ! I hope you're doing well. I was wondering if this repo still alive and if you can merge this pull request. It will be great to have it updated!

**Comment by cordoval** [comment]
ping @TheFrozenFire 

guys which one is the latest for this library cc @lucasiturbide ?

**Comment by lucasiturbide** [comment]
Hey @cordoval, I'm not sure if this repo is still alive. I started to use this PHP client for MBO SOAP API and when they added this new DataFunctionCSV I was forced to fork and make the update myself. I haven't updated it since then. I think it doesn't require an update yet

**Comment by cordoval** [comment]
true, thanks @lucasiturbide

**Pull request closed without merging**
